# environment variables
export JAVA_OPEN_JDK="/opt/homebrew/opt/openjdk"
export JAVA_11="/opt/homebrew/opt/openjdk@11"
export JAVA_17="/opt/homebrew/opt/openjdk@17"
export JAVA_HOME="$JAVA_17"
export IDEA_HOME="Applications/JetBrains Toolbox/IntelliJ IDEA Community Edition.app/Contents"
export IDEA_JDK="$JAVA_HOME"
export FLUTTER_HOME="$HOME/git/flutter/google/flutter"
export PUB_CACHE_HOME="$HOME/.pub-cache"
export ANDROID_HOME="/Users/cillian/Library/Android/sdk"
export STUDIO_HOME="Applications/JetBrains Toolbox/Android Studio.app/Contents"
export STUDIO_JDK="$JAVA_HOME"

# path
export PATH="$PATH:$JAVA_HOME/bin"
export PATH="$PATH:$IDEA_HOME/bin"
export PATH="$PATH:$FLUTTER_HOME/bin"
export PATH="$PATH:$ANDROID_HOME/emulator"
export PATH="$PATH:$ANDROID_HOME/platform-tools"
export PATH="$PATH:$STUDIO_HOME/bin"
