# environment variables
export JAVA_ASTUDIO="/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home"
export JAVA_OPENSDK="/usr/local/opt/openjdk"
export JAVA_HOME="$JAVA_ASTUDIO"
export ANDROID_HOME="/Users/cillian/Library/Android/sdk"
export STUDIO_HOME="/Applications/Android Studio.app/Contents"
export STUDIO_JDK="$JAVA_HOME"
export IDEA_HOME="/Applications/IntelliJ IDEA CE.app/Contents"
export FLUTTER_HOME="$HOME/git/flutter/google/flutter"
export DART_HOME="/usr/local/Cellar/dart/2.10.2"
export GO_HOME="/usr/local/go"
export GOPATH="$HOME/dev/go"
export CODEGEN_HOME="/usr/local/opt/swagger-codegen@2"

# path
export PATH="$PATH:$JAVA_HOME/bin"
export PATH="$PATH:$ANDROID_HOME/emulator"
export PATH="$PATH:$ANDROID_HOME/platform-tools"
export PATH="$PATH:$STUDIO_HOME/bin"
export PATH="$PATH:$IDEA_HOME/bin"
export PATH="$PATH:$FLUTTER_HOME/bin"
export PATH="$PATH:$DART_HOME/bin"
export PATH="$PATH:$GO_HOME/bin"
export PATH="$PATH:$CODEGEN_HOME/bin"
